version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    links:
      # - cache
      - db
    depends_on:
      - db

  # cache:
  #   image: redis
  #   ports:
  #     - 6379:6379

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./tmp/data/db:/data/db
