version: "3"

services:
  server:
    image: node
    build: .
    ports:
      - 80:8080
    links:
      - cache
      - db

  cache:
    image: redis
    ports:
      - 6379:6379

  db:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
